name: Deploy Next.js App to Azure

on:
  push:
    branches:
      - master  # Adjust this if you use a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23.x'  # Ensure this matches your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the Next.js app
      run: npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: nextjsdemo  # Replace with your Azure App Service name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'
